import { Product } from "./model";

export const mockProducts: Product[] = [
  // Smartphones
  {
    id: "1",
    name: "iPhone 15 Pro",
    price: 999,
    image: "/placeholder.jpg",
    category: "Smartphone",
    rating: 4.8,
    inStock: true,
    description:
      "The iPhone 15 Pro features a titanium design, A17 Pro chip, and advanced camera system with 5x optical zoom.",
    brand: "Apple",
    specs: {
      display: "6.1-inch Super Retina XDR",
      processor: "A17 Pro chip",
      memory: "8GB RAM",
      storage: "256GB",
      camera: "48MP main, 12MP ultra-wide, 12MP telephoto",
      battery: "3274 mAh",
    },
  },
  {
    id: "2",
    name: "Samsung Galaxy S24 Ultra",
    price: 1199,
    image: "/placeholder.jpg",
    category: "Smartphone",
    rating: 4.7,
    inStock: true,
    description:
      "Premium Android flagship with S Pen, AI features, and exceptional camera capabilities.",
    brand: "Samsung",
    specs: {
      display: "6.8-inch Dynamic AMOLED 2X",
      processor: "Snapdragon 8 Gen 3",
      memory: "12GB RAM",
      storage: "512GB",
      camera: "200MP main, dual telephoto, ultra-wide",
      battery: "5000 mAh",
    },
  },
  {
    id: "3",
    name: "Google Pixel 8 Pro",
    price: 899,
    image: "/placeholder.jpg",
    category: "Smartphone",
    rating: 4.6,
    inStock: true,
    description:
      "Google's flagship with advanced AI photography and pure Android experience.",
    brand: "Google",
    specs: {
      display: "6.7-inch LTPO OLED",
      processor: "Google Tensor G3",
      memory: "12GB RAM",
      storage: "256GB",
      camera: "50MP main, 48MP ultra-wide, 48MP telephoto",
      battery: "5050 mAh",
    },
  },
  {
    id: "4",
    name: "OnePlus 12",
    price: 799,
    image: "/placeholder.jpg",
    category: "Smartphone",
    rating: 4.5,
    inStock: true,
    description:
      "Flagship killer with Hasselblad camera system and super-fast charging.",
    brand: "OnePlus",
    specs: {
      display: "6.82-inch LTPO AMOLED",
      processor: "Snapdragon 8 Gen 3",
      memory: "16GB RAM",
      storage: "256GB",
      camera: "50MP main with Hasselblad",
      battery: "5400 mAh",
    },
  },

  // Laptops
  {
    id: "5",
    name: 'MacBook Pro M3 14"',
    price: 1599,
    image: "/placeholder.jpg",
    category: "Laptop",
    rating: 4.9,
    inStock: true,
    description:
      "Professional laptop with M3 chip, stunning Liquid Retina XDR display, and all-day battery life.",
    brand: "Apple",
    specs: {
      display: "14.2-inch Liquid Retina XDR",
      processor: "Apple M3",
      memory: "16GB unified memory",
      storage: "512GB SSD",
      graphics: "10-core GPU",
      battery: "Up to 22 hours",
    },
  },
  {
    id: "6",
    name: "Dell XPS 15",
    price: 1799,
    image: "/placeholder.jpg",
    category: "Laptop",
    rating: 4.7,
    inStock: true,
    description:
      "Premium Windows laptop with InfinityEdge display and powerful performance.",
    brand: "Dell",
    specs: {
      display: "15.6-inch OLED 3.5K",
      processor: "Intel Core i7-13700H",
      memory: "32GB DDR5",
      storage: "1TB NVMe SSD",
      graphics: "NVIDIA RTX 4060",
      battery: "86Wh",
    },
  },
  {
    id: "7",
    name: "ASUS ROG Zephyrus G14",
    price: 1499,
    image: "/placeholder.jpg",
    category: "Laptop",
    rating: 4.6,
    inStock: true,
    description:
      "Compact gaming powerhouse with AMD Ryzen and NVIDIA graphics.",
    brand: "ASUS",
    specs: {
      display: "14-inch QHD 165Hz",
      processor: "AMD Ryzen 9 7940HS",
      memory: "32GB DDR5",
      storage: "1TB PCIe 4.0 SSD",
      graphics: "NVIDIA RTX 4070",
      battery: "76Wh",
    },
  },
  {
    id: "8",
    name: "ThinkPad X1 Carbon Gen 11",
    price: 1399,
    image: "/placeholder.jpg",
    category: "Laptop",
    rating: 4.8,
    inStock: true,
    description:
      "Business ultrabook with legendary keyboard and military-grade durability.",
    brand: "Lenovo",
    specs: {
      display: "14-inch WUXGA IPS",
      processor: "Intel Core i7-1365U",
      memory: "16GB LPDDR5",
      storage: "512GB PCIe Gen 4 SSD",
      graphics: "Intel Iris Xe",
      battery: "57Wh",
    },
  },

  // Tablets
  {
    id: "9",
    name: 'iPad Pro 12.9"',
    price: 1099,
    image: "/placeholder.jpg",
    category: "Tablet",
    rating: 4.8,
    inStock: true,
    description:
      "Ultimate iPad experience with M2 chip and Liquid Retina XDR display.",
    brand: "Apple",
    specs: {
      display: "12.9-inch Liquid Retina XDR",
      processor: "Apple M2",
      memory: "8GB RAM",
      storage: "256GB",
      camera: "12MP wide, 10MP ultra-wide",
      battery: "40.88 Wh",
    },
  },
  {
    id: "10",
    name: "Samsung Galaxy Tab S9 Ultra",
    price: 999,
    image: "/placeholder.jpg",
    category: "Tablet",
    rating: 4.6,
    inStock: true,
    description:
      "Premium Android tablet with large display and S Pen included.",
    brand: "Samsung",
    specs: {
      display: "14.6-inch Dynamic AMOLED 2X",
      processor: "Snapdragon 8 Gen 2",
      memory: "12GB RAM",
      storage: "256GB",
      camera: "13MP dual rear camera",
      battery: "11200 mAh",
    },
  },
  {
    id: "11",
    name: "iPad Air",
    price: 599,
    image: "/placeholder.jpg",
    category: "Tablet",
    rating: 4.7,
    inStock: true,
    description:
      "Powerful and versatile iPad with M1 chip and beautiful display.",
    brand: "Apple",
    specs: {
      display: "10.9-inch Liquid Retina",
      processor: "Apple M1",
      memory: "8GB RAM",
      storage: "64GB",
      camera: "12MP wide camera",
      battery: "28.6 Wh",
    },
  },
  {
    id: "12",
    name: "Microsoft Surface Pro 9",
    price: 899,
    image: "/placeholder.jpg",
    category: "Tablet",
    rating: 4.5,
    inStock: false,
    description: "2-in-1 Windows tablet that replaces your laptop.",
    brand: "Microsoft",
    specs: {
      display: "13-inch PixelSense Flow",
      processor: "Intel Core i5-1235U",
      memory: "8GB LPDDR5",
      storage: "256GB SSD",
      camera: "10MP rear, 5MP front",
      battery: "47.7 Wh",
    },
  },

  // Accessories
  {
    id: "13",
    name: "AirPods Pro 2",
    price: 249,
    image: "/placeholder.jpg",
    category: "Accessories",
    rating: 4.7,
    inStock: true,
    description:
      "Active noise cancellation, personalized spatial audio, and MagSafe charging case.",
    brand: "Apple",
    specs: {
      type: "True wireless earbuds",
      connectivity: "Bluetooth 5.3",
      battery: "6 hours (up to 30 with case)",
      features: "ANC, Transparency mode, Spatial audio",
      water: "IPX4 rated",
    },
  },
  {
    id: "14",
    name: "Samsung Galaxy Watch 6 Classic",
    price: 399,
    image: "/placeholder.jpg",
    category: "Accessories",
    rating: 4.6,
    inStock: true,
    description:
      "Premium smartwatch with rotating bezel and comprehensive health tracking.",
    brand: "Samsung",
    specs: {
      display: "1.5-inch Super AMOLED",
      processor: "Exynos W930",
      memory: "2GB RAM, 16GB storage",
      battery: "425 mAh",
      features: "GPS, Heart rate, Sleep tracking",
      water: "5ATM + IP68",
    },
  },
  {
    id: "15",
    name: "Sony WH-1000XM5",
    price: 399,
    image: "/placeholder.jpg",
    category: "Accessories",
    rating: 4.8,
    inStock: true,
    description:
      "Industry-leading noise canceling headphones with exceptional sound quality.",
    brand: "Sony",
    specs: {
      type: "Over-ear headphones",
      connectivity: "Bluetooth 5.2",
      battery: "30 hours with ANC",
      features: "Best-in-class ANC, LDAC support",
      drivers: "30mm",
    },
  },
  {
    id: "16",
    name: "Apple Pencil (2nd gen)",
    price: 129,
    image: "/placeholder.jpg",
    category: "Accessories",
    rating: 4.7,
    inStock: true,
    description:
      "Precision stylus for iPad Pro and iPad Air with wireless charging.",
    brand: "Apple",
    specs: {
      compatibility: "iPad Pro, iPad Air",
      charging: "Wireless magnetic attachment",
      features: "Pressure sensitivity, tilt detection",
      latency: "9ms",
    },
  },
];
